name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [10, 11, 12, 13, 14]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - run: node --version
      - run: npm install
      - run: npm install --only=dev
      - run: npm install canvas --no-save
      - run: npm run build
      - run: npm run lint
      - run: npm test
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_KEY: ${{ secrets.TEST_KEY }}
